baseURL = "http://hugotestsite.michellegrassi.dk"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"

[params]
extracssfiles          = [ "/css/override.css" ]   

[[menu.main]]
name                   = "Blog"
weight                 = 20
identifier             = "blog"
url                    = "/blog/"


[[menu.main]]
name                   = "About"
weight                 = 15
identifier             = "about"
url                    = "/about/"


[[menu.main]]
name                   = "Contact"
weight                 = 10
identifier             = "contact"
url                    = "/contact/"

[[menu.main]]
name                   = "Portfolio"
weight                 = 5
identifier             = "portfolio"
url                    = "/portfolio/"
